### ISSUE TITLE
Is this plugins still usable

### ISSUE THREAD

**Issue by nathanramli** [mschnitzer/sockets#1]
Hello @mschnitzer 
I have found this plugins, and would to use it.

Is this plugins still usable, because it seems like deprecated. Did you want to still maintaining this?

**Comment by mschnitzer** [comment]
Hi @nathanramli ,

nope I'm actually no longer working on this plugin and I've no information if it's still usable. It was one of my first plugins I created for SA:MP and my C++ knowledge back then was very little, so I would encourage you to use a better supported socket plugin.

**Comment by nathanramli** [comment]
Thanks for your response and letting me know.
